version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn samples.wsgi:application --bind 0.0.0.0:8000
    networks:
      - nginx_network
      - db_network
    volumes:
      - static_volume:/home/app/static/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    restart: always
    image: postgres:12
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/static/
    networks:
      - nginx_network
    ports:
      - 8000:80
    depends_on:
      - web


networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
    
volumes:
  postgres_data:
  static_volume:
